CREATE TABLE IF NOT EXISTS leads (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    name VARCHAR(200) NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(254) NULL,
    company VARCHAR(200) NULL,
    comment TEXT NULL,
    source VARCHAR(64) NOT NULL,
    page_url VARCHAR(2048) NULL,
    referrer VARCHAR(2048) NULL,
    utm_source VARCHAR(255) NULL,
    utm_medium VARCHAR(255) NULL,
    utm_campaign VARCHAR(255) NULL,
    utm_content VARCHAR(255) NULL,
    utm_term VARCHAR(255) NULL,
    yclid VARCHAR(255) NULL,
    consent_at DATETIME NULL,
    consent_text_version VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    note TEXT NULL,
    next_step VARCHAR(500) NULL,
    contacted_at DATETIME NULL,
    owner VARCHAR(200) NULL,
    synced_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_leads_request_id (request_id),
    KEY ix_leads_created_at (created_at),
    KEY ix_leads_status (status),
    KEY ix_leads_synced_at (synced_at)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS subscriptions (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME NOT NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(254) NULL,
    page_url VARCHAR(2048) NULL,
    source VARCHAR(64) NOT NULL,
    utm_source VARCHAR(255) NULL,
    utm_medium VARCHAR(255) NULL,
    utm_campaign VARCHAR(255) NULL,
    utm_content VARCHAR(255) NULL,
    utm_term VARCHAR(255) NULL,
    yclid VARCHAR(255) NULL,
    consent_at DATETIME NOT NULL,
    consent_text_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    unsubscribed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_subscriptions_request_id (request_id),
    KEY ix_subscriptions_created_at (created_at),
    KEY ix_subscriptions_status (status)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_limit (
    ip_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    window_start DATETIME NOT NULL,
    hits INT NOT NULL,
    PRIMARY KEY (ip_hash, window_start),
    KEY ix_rate_limit_window_start (window_start)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
